config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "ask", to: "pages#ask", as: :ask
  get "answer", to: "pages#answer", as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/PagesController.rb
class PagesController < ApplicationController
  def home
  end

  def ask
  end

  def answer
    @question = params[:question]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/answer.html.erb
<h1>Answer</h1>

<p>You:  <%= @question  %></p>


<% if @question ==  "I am going to work" %>
    <p>Coach: Great!</p>
<% elsif @question[-1] == "?" %>
    <p>Coach: Silly question, get dressed and go to work!</p>
<% else %>
    <p>Coach: I don't care, get dressed and go to work!</p>
<% end %>

<%= link_to "Ask a new Question!", ask_path, class: "btn btn-link"  %>

app/views/pages/ask.html.erb
<h1>Ask a Question!</h1>

<%# Damit das Formular direkt nach /answer schickt (statt nach /ask):%>
<form action="<%= answer_path %>" data-turbo="false">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>

app/views/pages/home.html.erb
<h1>Home</h1>